version = "1.0"

[main]
name = "Conduwuit configuration"
services = ["__APP__"]

    [main.registration]
    name = "User registration"

        [main.registration.registration]
        ask.en = "Should registration be enabled?"
        type = "boolean"
        yes = "true"
        no = "false"
        bind = "allow_registration:__INSTALL_DIR__/conduwuit.toml"

        [main.registration.registration_token]
        ask.en = "What should your registration token be?"
        visible = "registration"
        type = "string"
        bind = "registration_token:__INSTALL_DIR__/conduwuit.toml"

        [main.registration.federation]
        ask.en = "Allow Federation"
        type = "boolean"
        yes = "true"
        no = "false"
        help = "Communicate with other homeservers of the Matrix Federation."
        bind = "allow_federation:__INSTALL_DIR__/conduwuit.toml"

        [main.registration.account_suffix]
        ask.en = "Text/emoji to automatically add to the end all display names? (leave blank for nothing)"
        type = "string"
        help = "This is not permanent and can be changed by the user"
        bind = "new_user_displayname_suffix:__INSTALL_DIR__/conduwuit.toml"

        [main.registration.sync_user_create]
        type = "boolean"
        ask.en = "Should new yunohost users be automatically added"
        help.en = "This will automatically create accounts for any yunohost users added after installation, restarting the server in the process"

        [main.registration.sync_user_delete]
        type = "boolean"
        visible = "sync_user_create"
        ask.en = "Should their conduwuit accounts also be deactivated their yunohost accounts are deleted"
        help.en = "WARNING! This will PERMANENTLY deactivate accounts, meaning conduwuit users with the same username can never be created again"
    # Commented out because it prevents the config panel from loading
    # [main.servers]
    # name = "External services to connect to"
    #
    #     [main.servers.jitsi_server]
    #     ask.en = "Jitsi server address for conferencing?"
    #     ask.fr = "Adresse du serveur Jitsi pour les conférences ?"
    #     type = "string"
    #     example = "domain.org"
    #     bind = "im.vector.riot.jitsi>preferredDomain:/etc/nginx/conf.d/__SERVER_NAME__.d/__APP___server_name.conf"
    #     default = "jitsi.riot.im"

    # This config panel section has been removed as the actions can be done
    # without restarting the server using the admin chat
    #
    # If re-added, this panel will need to be separated into a user_management.users.action
    # rather than main.users_action
    #
    # [main.users_add]
    # name = "Add a user (NOTE: These actions will shut down your server for a very short time then restart it)"
    #     [main.users_add.username]
    #     type = "string"
    #     bind = "null" # this value won't be saved as a setting, it's ephemeral and only relevant for the action
    #     ask = "username"
    #
    #     [main.users_add.password]
    #     type = "password"
    #     bind = "null" # this value won't be saved as a setting, it's ephemeral and only relevant for the action
    #     ask = "password"
    #
    #     [main.users_add.add_user]
    #     type = "button"
    #     ask = "Add"
    #     # the button is clickable only once the previous values are provided
    #     enabled = "username && password"
    #
    # [main.users_deactivate]
    # name = "Deactivate a user (WARNING: This prevents them from ever logging in again)"
    #     [main.users_deactivate.username]
    #     type = "string"
    #     bind = "null" # this value won't be saved as a setting, it's ephemeral and only relevant for the action
    #     ask = "username"
    #
    #     [main.users_deactivate.confirm]
    #     type = "boolean"
    #     yes = "I understand"
    #     no = "What I'm confused ?? (look above)"
    #     ask = "I understand what deactivating a user means and I would like to proceed"
    #
    #     [main.users_deactivate.deactivate_user]
    #     type = "button"
    #     # the button is clickable only once the previous values are provided
    #     enabled = "username && confirm"
    #     style = "warning"
    #     ask = "PERMANENTLY DEACTIVATE USER"
