#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "conduwuit"
name = "Conduwuit"
description.en = "A very cool, featureful fork of conduit, A lightweight, open source Matrix server."

version = "v0.5.0-rc~ynh1"

maintainers = ["eric_G"]

[upstream]
license = " Apache-2.0"
website = "https://conduwuit.puppyirl.gay/"
demo = "https://transfem.dev"
admindoc = "https://conduwuit.puppyirl.gay"
code = "https://github.com/girlbossceo/conduwuit"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = [ "arm64", "amd64" ]
multi_instance = false

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[antifeatures]
arbitrary-limitations.en = "Conduwuit is currently in beta. This means you can join and participate in most Matrix rooms, but not all features are supported and you might run into some bugs."

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"
    help.en = "If you want to be able to federate with other servers, you should keep the default choice, visitors"
    help.fr = "Si vous souhaitez pouvoir fédérer votre serveur avec d'autres, vous devez laisser le choix par défaut, visiteurs"

    [install.server_name]
    type = "domain"
    ask.en = "Select the display name for your Conduwuit server"
    ask.fr = "Sélectionnez le nom d'affichage pour votre serveur Conduwuit"
    help.en = "If you choose domain.tld, your Matrix user-ids will be looking like @user:domain.tld instead of @user:conduwuit.domain.tld"
    help.fr = "Si vous choisissez domain.tld, vos identifiants Matrix ressembleront à @utilisateur:domain.tld plutôt que @utilisateur:conduwuit.domain.tld"

    [install.registration]
    type = "boolean"
    ask.en = "Should the server allow any visitor to register as a user?"
    ask.fr = "Le serveur doit-il permettre à quiconque de s'enregistrer comme utilisateur?"
    help.en = "A configurable invite token must be given to new users to register (A default one is generated during install)"
    default = false

    [install.sync_users]
    type = "boolean"
    ask.en = "Should new yunohost users be automatically added"
    help.en = "This will automatically create accounts for any yunohost users added after installation, restarting the server in the process"
    default = true

    [install.admin]
    type = "user"

    [install.password]
    type = "password"
    ask.en = "Enter the password for the admin account"

[resources]

    [resources.sources]

        [resources.sources.main]
        in_subdir = false
        extract = false
        rename = "conduwuit"

        amd64.url = "https://github.com/girlbossceo/conduwuit/releases/download/v0.5.0-rc/static-x86_64-linux-musl"
        amd64.sha256 = "92eaed71b1a349ac9cc5792fe176bf84ab5e4b84774d4af1e819d5e757b1ce0c"

        arm64.url = "https://github.com/girlbossceo/conduwuit/releases/download/v0.5.0-rc/static-aarch64-linux-musl"
        arm64.sha256 = "0c13128a6f001118c131dafe50ec99b16629eed8515dfc4c4070d23f458329f6"

        autoupdate.strategy = "latest_github_release"

    [resources.system_user]

    [resources.data_dir]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    main.show_tile = false

    server_api.url = "/_matrix"
    server_api.label = "Server access for client apps."
    server_api.show_tile = false
    server_api.allowed = "visitors"
    server_api.auth_header = false
    server_api.protected = true

    server_client_infos.url = "/.well-known/matrix"
    server_client_infos.label = "Server info for federation. (well-known)"
    server_client_infos.show_tile = false
    server_client_infos.allowed = "visitors"
    server_client_infos.auth_header = false
    server_client_infos.protected = true

    [resources.ports]
    conduwuit.default = 8008

    conduwuit_tls.default = 8448
    conduwuit_tls.exposed = "TCP"
