#!/bin/bash
source /usr/share/yunohost/helpers

if [ "$(ynh_app_setting_get --app=__APP__ --key=sync_user_create)" -eq 1 ]; then
    yunohost service stop __APP__
    ynh_print_info "Adding a Conduwuit user"
    cd __INSTALL_DIR__
    # Using the yunohost v1 logging helpers to stop password being shown in the logs
    ynh_print_OFF
    ynh_exec_fully_quiet ./conduwuit -c conduwuit.toml --execute "users create-user $YNH_USER_USERNAME $YNH_USER_PASSWORD" --execute "server shutdown"
    ynh_print_ON
    yunohost service start __APP__
fi
