#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# DECLARE DATA AND CONF FILES TO BACKUP
#=================================================
ynh_print_info --message="Declaring files to be backed up..."

#=================================================
# BACKUP THE APP MAIN DIR
#=================================================

ynh_backup "$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================

ynh_backup "/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_backup "/etc/systemd/system/$app.service"

# Backup only server name config if it exist
if [ -e "/etc/nginx/conf.d/${server_name}.d/${app}_server_name.conf" ]; then
    ynh_backup "/etc/nginx/conf.d/${server_name}.d/${app}_server_name.conf"
fi

# Backup hooks
ynh_backup "/etc/yunohost/hooks.d/post_user_create/50-$app"
ynh_backup "/etc/yunohost/hooks.d/post_user_delete/50-$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info "Backup script completed for $app. (YunoHost will then actually copy those files to the archive)."
