#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop" --log_path="systemd"

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

ynh_config_change_url_nginx

#=================================================
# UPDATE OTHER APP CONFIGS
#=================================================
turn_password=$(ynh_app_setting_get --app="coturn" --key=turnserver_pwd)
turn_external_port=$(ynh_app_setting_get --app="coturn" --key=port_turnserver_tls)

# Update .well-known (not sure if yunohost automatically does this?)
if yunohost --output-as plain domain list | grep -q "^$server_name$"
then
    ynh_config_add --template="server_name.conf" --destination="/etc/nginx/conf.d/${server_name}.d/${app}_server_name.conf"
fi

# Update conduwuit config
ynh_config_add --template="conduwuit.toml" --destination="$install_dir/conduwuit.toml"

chmod 400 "$install_dir/conduwuit.toml"
chown "$app:$app" "$install_dir/conduwuit.toml"
#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
