#!/bin/bash

# source ./_common.sh
# source /usr/share/yunohost/helpers
#
# run__add_user() {
#     myynh_add_user $username $password
# }
#
# run__deactivate_user() {
#     myynh_deactivate_user $username
# }
