#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

federation="true"
registration_token="$(ynh_string_random --length=8)"
account_suffix=""

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================

ynh_app_setting_set --key=federation --value=$federation
ynh_app_setting_set --key=registration_token --value=$registration_token
ynh_app_setting_set --key=sync_users --value=$sync_users
ynh_app_setting_set --key=account_suffix --value=$account_suffix
ynh_app_setting_set --key=jitsi_server --value=$jitsi_server
ynh_app_setting_set --key=server_name --value=$server_name

#=================================================
# SETUP HOOKS
#=================================================

ynh_replace --match="__APP__" --replace="$app" --file="../hooks/post_user_create"
ynh_replace --match="__INSTALL_DIR__" --replace="$install_dir" --file="../hooks/post_user_create"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

chown -R "$app:root" "$install_dir"
chmod +x "$install_dir/conduwuit"

#=================================================
# INSTALL COTURN IF NOT INSTALLED
#=================================================
# This is taken from https://github.com/YunoHost-Apps/prosody_ynh/blob/testing/scripts/install#L15C1-L22C79
if ! yunohost app list | grep -q "id: coturn"; then
        echo "Coturn is not installed. Installing... "
        yunohost tools update
        yunohost app install coturn --force --args "domain=$domain"
fi

turn_password=$(ynh_app_setting_get --app="coturn" --key=turnserver_pwd)
turn_external_port=$(ynh_app_setting_get --app="coturn" --key=port_turnserver)
#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template="conduwuit.toml" --destination="$install_dir/conduwuit.toml"

chmod 400 "$install_dir/conduwuit.toml"
chown "$app:$app" "$install_dir/conduwuit.toml"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create .well-known redirection for access by federation
if yunohost --output-as plain domain list | grep -q "^$server_name$"
then
    ynh_config_add --template="server_name.conf" --destination="/etc/nginx/conf.d/${server_name}.d/${app}_server_name.conf"
fi

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add $app --description="Chat server powered by Matrix" --log="/var/log/$app/$app.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start" --log_path="systemd"

#=================================================
# CREATE ADMIN USER
#=================================================
ynh_script_progression "Adding admin user..."

myynh_add_user $admin $password

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
